# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/805/bin/cmake

# The command to remove a file.
RM = /snap/cmake/805/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yanis/Bureau/Projets/thread-vs-fork-in-cpp---Matrices

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yanis/Bureau/Projets/thread-vs-fork-in-cpp---Matrices

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/805/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/805/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yanis/Bureau/Projets/thread-vs-fork-in-cpp---Matrices/CMakeFiles /home/yanis/Bureau/Projets/thread-vs-fork-in-cpp---Matrices//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yanis/Bureau/Projets/thread-vs-fork-in-cpp---Matrices/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matrixcpp

# Build rule for target.
matrixcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrixcpp
.PHONY : matrixcpp

# fast build rule for target.
matrixcpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/build
.PHONY : matrixcpp/fast

# target to build an object file
src/Matrix.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/Matrix.o
.PHONY : src/Matrix.o

# target to preprocess a source file
src/Matrix.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/Matrix.i
.PHONY : src/Matrix.i

# target to generate assembly for a file
src/Matrix.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/Matrix.s
.PHONY : src/Matrix.s

# target to build an object file
src/Serializer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/Serializer.o
.PHONY : src/Serializer.o

# target to preprocess a source file
src/Serializer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/Serializer.i
.PHONY : src/Serializer.i

# target to generate assembly for a file
src/Serializer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/Serializer.s
.PHONY : src/Serializer.s

# target to build an object file
src/SharedCalculator.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/SharedCalculator.o
.PHONY : src/SharedCalculator.o

# target to preprocess a source file
src/SharedCalculator.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/SharedCalculator.i
.PHONY : src/SharedCalculator.i

# target to generate assembly for a file
src/SharedCalculator.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/SharedCalculator.s
.PHONY : src/SharedCalculator.s

# target to build an object file
src/main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/main.o
.PHONY : src/main.o

# target to preprocess a source file
src/main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/main.i
.PHONY : src/main.i

# target to generate assembly for a file
src/main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrixcpp.dir/build.make CMakeFiles/matrixcpp.dir/src/main.s
.PHONY : src/main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... matrixcpp"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/Serializer.o"
	@echo "... src/Serializer.i"
	@echo "... src/Serializer.s"
	@echo "... src/SharedCalculator.o"
	@echo "... src/SharedCalculator.i"
	@echo "... src/SharedCalculator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

